# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Demo.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QMainWindow
from PyQt5.QtCore import *
from PyQt5.QtWidgets import *
from PyQt5.QtGui import *

import  os
import sys

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tbnOpen = QtWidgets.QPushButton(self.centralwidget)
        self.tbnOpen.setGeometry(QtCore.QRect(190, 20, 101, 41))
        self.tbnOpen.setObjectName("tbnOpen")
        self.tbnClose = QtWidgets.QPushButton(self.centralwidget)
        self.tbnClose.setGeometry(QtCore.QRect(312, 20, 121, 41))
        self.tbnClose.setObjectName("tbnClose")
        self.label_1 = QtWidgets.QLabel(self.centralwidget)
        self.label_1.setGeometry(QtCore.QRect(20, 80, 191, 41))
        self.label_1.setObjectName("label_1")
        self.cBPortName = QtWidgets.QComboBox(self.centralwidget)
        self.cBPortName.setGeometry(QtCore.QRect(20, 20, 151, 41))
        self.cBPortName.setObjectName("cBPortName")
        self.tEReceiveData = QtWidgets.QTextEdit(self.centralwidget)
        self.tEReceiveData.setGeometry(QtCore.QRect(20, 110, 761, 371))
        self.tEReceiveData.setObjectName("tEReceiveData")
        self.lESend = QtWidgets.QLineEdit(self.centralwidget)
        self.lESend.setGeometry(QtCore.QRect(20, 510, 631, 31))
        self.lESend.setObjectName("lESend")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 480, 191, 41))
        self.label_2.setObjectName("label_2")
        self.tbnSend = QtWidgets.QToolButton(self.centralwidget)
        self.tbnSend.setGeometry(QtCore.QRect(670, 510, 111, 31))
        self.tbnSend.setObjectName("tbnSend")
        self.label_Time = QtWidgets.QLabel(self.centralwidget)
        self.label_Time.setGeometry(QtCore.QRect(470, 24, 301, 31))
        self.label_Time.setObjectName("label_Time")
        self.tbnClear = QtWidgets.QToolButton(self.centralwidget)
        self.tbnClear.setGeometry(QtCore.QRect(670, 70, 111, 31))
        self.tbnClear.setObjectName("tbnClear")
        self.pBSelect = QtWidgets.QPushButton(self.centralwidget)
        self.pBSelect.setGeometry(QtCore.QRect(540, 70, 101, 31))
        self.pBSelect.setObjectName("pBSelect")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(430, 70, 93, 28))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.tbnOpen.setText(_translate("MainWindow", "打开端口"))
        self.tbnClose.setText(_translate("MainWindow", "关闭端口"))
        self.label_1.setText(_translate("MainWindow", "数据接收"))
        self.label_2.setText(_translate("MainWindow", "数据发送"))
        self.tbnSend.setText(_translate("MainWindow", "发送"))
        self.label_Time.setText(_translate("MainWindow", "TextLabel"))
        self.tbnClear.setText(_translate("MainWindow", "清空数据"))
        self.pBSelect.setText(_translate("MainWindow", "选择画笔"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))


class Ui_Demo(QtWidgets.QMainWindow):
    def __init__(self):
        super(Ui_Demo, self).__init__()
        self._ui = Ui_MainWindow()
        self._ui.setupUi(self)



if __name__ == '__main__':

    app = QApplication(sys.argv)
    MainWindow = Ui_Demo()
    MainWindow.show()
    sys.exit(app.exec_())
